name: cust-churn

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip

  - pip:
      - mlflow
      - pandas
      - numpy
      - scikit-learn
      - scipy
      - cloudpickle
