name: CI MLflow Training

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      # =====================================
      # Checkout Repository
      # =====================================
    
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      # =====================================
      # Setup Python
      # =====================================
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
    
      # =====================================
      # Check Environment
      # =====================================
    
      - name: Check Environment
        run: |
          echo "Python Version"
          python --version
    
          echo "Pip Version"
          pip --version
    
      # =====================================
      # Install Dependencies
      # =====================================
    
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn scipy cloudpickle
    
      # =====================================
      # Run MLflow Project
      # =====================================
    
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager local
    
      # =====================================
      # Get Latest MLflow Run ID
      # =====================================
    
      - name: Get Latest MLflow Run ID
        run: |
          python - <<EOF
          import os
    
          latest_run = None
    
          for root, dirs, files in os.walk("mlruns"):
              for d in dirs:
                  if len(d) > 20:
                      latest_run = d
    
          if latest_run:
              with open("latest_run_id.txt", "w") as f:
                  f.write(latest_run)
    
              print("Latest Run ID:", latest_run)
          else:
              print("No MLflow run found")
          EOF
    
      # =====================================
      # Commit Run ID
      # =====================================
    
      - name: Commit Run ID
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
          git add latest_run_id.txt
    
          git commit -m "Update latest MLflow run ID [skip ci]" || echo "No changes"
    
      # =====================================
      # Push To Main
      # =====================================
    
      - name: Push Changes
        run: |
          git push origin HEAD:main
    
      # =====================================
      # Complete Job
      # =====================================
    
      - name: Complete Job
        run: |
          echo "Workflow completed successfully"
